In [1]:
from buildstock_query import BuildStockQuery
import pandas as pd

In [2]:
# autoreload
%load_ext autoreload
%autoreload 2

In [ ]:
my_run = BuildStockQuery('ghpphase2','buildstock_sdr',
                         ("comstock_amy2018_r2_2025_md_agg_national_vu",
                          "comstock_amy2018_r2_2025_ts_by_state_vu",
                          "comstock_amy2018_r2_2025_md_agg_national_vu"),
                        buildstock_type='comstock',
                        db_schema="comstock_oedi",
                        skip_reports=False)

INFO:buildstock_query.query_core:Loading ('comstock_amy2018_r2_2025_md_agg_national_vu', 'comstock_amy2018_r2_2025_ts_by_state_vu', 'comstock_amy2018_r2_2025_md_agg_national_vu') ...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:buildstock_query.main:Getting Success counts...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)
INFO:buildstock_query.report_query:Checking integrity with ts_tables ...
/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 62, 'completed': 0, 'failed': 0}

          success  inapplicable  fail       Sum  Applied %  no-chng  bad-chng  \
upgrade
0        158952.0           0.0     0  158952.0        0.0      0.0       0.0
1         95297.0      218555.0     0  313852.0       30.4      0.0       0.0
10        95214.0      218638.0     0  313852.0       30.3      0.0       0.0
11       132852.0      181000.0     0  313852.0       42.3      0.0       0.0
12       132834.0      181018.0     0  313852.0       42.3      0.0       0.0
...           ...           ...   ...       ...        ...      ...       ...
60       282204.0       31648.0     0  313852.0       89.9      0.0       0.0
61       313842.0          10.0     0  313852.0      100.0      0.0       0.0
7         95257.0      218595.0     0  313852.0       30.4      0.0       0.0
8         95300.0      218552.0     0  313852.0       30.4      0.0       0.0
9         95258.0      218594.0     0  313852.0       30.4      0.0       0.0

         ok-chng  true-bad-chng  true-ok-chng  null  any  no-chng %  \
upgrade
0            0.0            0.0           0.0   0.0  0.0        0.0
1            0.0            0.0           0.0   0.0  0.0        0.0
10           0.0            0.0           0.0   0.0  0.0        0.0
11           0.0            0.0           0.0   0.0  0.0        0.0
12           0.0            0.0           0.0   0.0  0.0        0.0
...          ...            ...           ...   ...  ...        ...
60           0.0            0.0           0.0   0.0  0.0        0.0
61           0.0            0.0           0.0   0.0  0.0        0.0
7            0.0            0.0           0.0   0.0  0.0        0.0
8            0.0            0.0           0.0   0.0  0.0        0.0
9            0.0            0.0           0.0   0.0  0.0        0.0

         bad-chng %  ok-chng %  true-ok-chng %  true-bad-chng %
upgrade
0               0.0        0.0             0.0              0.0
1               0.0        0.0             0.0              0.0
10              0.0        0.0             0.0              0.0
11              0.0        0.0             0.0              0.0
12              0.0        0.0             0.0              0.0
...             ...        ...             ...              ...
60              0.0        0.0             0.0              0.0
61              0.0        0.0             0.0              0.0
7               0.0        0.0             0.0              0.0
8               0.0        0.0             0.0              0.0
9               0.0        0.0             0.0              0.0

[62 rows x 17 columns]

INFO:buildstock_query.query_core:Submitted queries[0] (f8ad1c66-5428-48bd-b842-d149dbb72a2c)
INFO:buildstock_query.query_core:Submitted queries[1] (04d50590-1ec5-4dbf-ac3b-4eb355e6fd26)
INFO:buildstock_query.query_core:Submitted queries[2] (ea408670-b2ec-4613-b9fe-440b83cf7f40)
INFO:buildstock_query.query_core:{'submitted': 3, 'running': 1, 'pending': 61, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[3] (202491dd-0fe3-4972-91df-b9c39aa21eb3)
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 58, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 58, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 58, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 58, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 58, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[4] (e6ff55fb-8dce-4b70-925e-dbbaaba8a3c8)
INFO:buildstock_query.query_core:{'submitted': 5, 'running': 4, 'pending': 57, 'completed': 1, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[5] (3afd70e2-c963-47cb-9e4f-dc1af8d70b78)
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 4, 'pending': 56, 'completed': 2, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 6, 'running': 4, 'pending': 56, 'completed': 2, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[6] (d6d6a572-1444-4151-bc02-b5067d106b9c)
INFO:buildstock_query.query_core:Submitted queries[7] (e792b5ae-9aeb-4fa4-a237-904611cdf8ec)
INFO:buildstock_query.query_core:{'submitted': 8, 'running': 4, 'pending': 54, 'completed': 3, 'failed': 1}
INFO:buildstock_query.query_core:Submitted queries[8] (5f42048d-96ec-435c-afd6-f79f669f48b8)
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 4, 'pending': 53, 'completed': 3, 'failed': 2}
INFO:buildstock_query.query_core:Submitted queries[9] (7d878e3f-2e07-43dc-8713-9bea5d1b4e19)
INFO:buildstock_query.query_core:{'submitted': 10, 'running': 4, 'pending': 52, 'completed': 3, 'failed': 3}
INFO:buildstock_query.query_core:{'submitted': 10, 'running': 3, 'pending': 52, 'completed': 3, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[10] (a26fb949-f897-423b-b1c6-b1e5b64a38b7)
INFO:buildstock_query.query_core:Submitted queries[11] (8870d91e-29c2-4775-9e61-7bdd5c41b04c)
INFO:buildstock_query.query_core:{'submitted': 12, 'running': 4, 'pending': 50, 'completed': 4, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[12] (6fa15760-7bfa-4340-b25b-1356b20ff224)
INFO:buildstock_query.query_core:Submitted queries[13] (0b73609e-0979-478a-af0e-c8475a0ef2e6)
INFO:buildstock_query.query_core:Submitted queries[14] (d994b3a1-bda9-4a1f-be00-f2726d31d804)
INFO:buildstock_query.query_core:{'submitted': 15, 'running': 4, 'pending': 47, 'completed': 7, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[15] (609eacbb-eb3c-465b-ad2c-9002c087f20d)
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 46, 'completed': 8, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 46, 'completed': 8, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 16, 'running': 4, 'pending': 46, 'completed': 8, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[16] (691ee632-2655-416c-bc16-f554aff61ab9)
INFO:buildstock_query.query_core:Submitted queries[17] (73e6ff09-02b5-4931-ade1-cc294f8063bd)
INFO:buildstock_query.query_core:Submitted queries[18] (8d8a0100-68a2-4872-80af-64f43d9774fc)
INFO:buildstock_query.query_core:Submitted queries[19] (7a567975-d3f0-4a0f-9a3c-3798d523b4a2)
INFO:buildstock_query.query_core:{'submitted': 20, 'running': 4, 'pending': 42, 'completed': 12, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 20, 'running': 4, 'pending': 42, 'completed': 12, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 20, 'running': 4, 'pending': 42, 'completed': 12, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 20, 'running': 4, 'pending': 42, 'completed': 12, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[20] (b0d9f34e-e783-41e1-93ad-fcc60d9a8209)
INFO:buildstock_query.query_core:Submitted queries[21] (2cc3372e-6812-4988-85de-1e7575968589)
INFO:buildstock_query.query_core:Submitted queries[22] (b185e5cf-d755-4c4f-99da-7b7586867634)
INFO:buildstock_query.query_core:Submitted queries[23] (866068c1-b835-4771-8850-16c7f7e463ad)
INFO:buildstock_query.query_core:{'submitted': 24, 'running': 4, 'pending': 38, 'completed': 16, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 24, 'running': 4, 'pending': 38, 'completed': 16, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 24, 'running': 4, 'pending': 38, 'completed': 16, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 24, 'running': 3, 'pending': 38, 'completed': 17, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[24] (aaad27cc-dfde-479a-8d8e-828717d96ca7)
INFO:buildstock_query.query_core:Submitted queries[25] (6c6017d3-4fce-4c65-8be8-a0289b8dfdce)
INFO:buildstock_query.query_core:Submitted queries[26] (6a221891-d37b-4726-948b-24d78b7ff953)
INFO:buildstock_query.query_core:Submitted queries[27] (7db73610-81cf-4c46-99a7-3bde33ddbab3)
INFO:buildstock_query.query_core:{'submitted': 28, 'running': 4, 'pending': 34, 'completed': 20, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 28, 'running': 4, 'pending': 34, 'completed': 20, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 28, 'running': 4, 'pending': 34, 'completed': 20, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 28, 'running': 0, 'pending': 34, 'completed': 24, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[28] (109cb087-5737-465b-a114-ca0f285a4a04)
INFO:buildstock_query.query_core:Submitted queries[29] (9029b0c8-9508-4974-8ec8-f9c5c3b04320)
INFO:buildstock_query.query_core:Submitted queries[30] (ae34b3f6-f132-4d2f-ae66-e984a6111a23)
INFO:buildstock_query.query_core:Submitted queries[31] (1a6d15a7-448b-4d2c-9bfa-b0504ee0fd50)
INFO:buildstock_query.query_core:{'submitted': 32, 'running': 4, 'pending': 30, 'completed': 24, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 32, 'running': 4, 'pending': 30, 'completed': 24, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 32, 'running': 4, 'pending': 30, 'completed': 24, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[32] (bae86845-b28e-4c4a-a8b2-ef4b68f10f66)
INFO:buildstock_query.query_core:Submitted queries[33] (46eff575-a445-4aa1-8cf7-9411ce934913)
INFO:buildstock_query.query_core:Submitted queries[34] (cf2b65f8-9e9f-48a9-8e46-f3cac69c0c46)
INFO:buildstock_query.query_core:{'submitted': 35, 'running': 3, 'pending': 27, 'completed': 28, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[35] (c773b9e0-5aab-414b-8fe9-a06645029911)
INFO:buildstock_query.query_core:{'submitted': 36, 'running': 4, 'pending': 26, 'completed': 28, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 36, 'running': 4, 'pending': 26, 'completed': 28, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[36] (6857ffdc-2dd6-4c3a-a763-d2cc9ce2ce33)
INFO:buildstock_query.query_core:Submitted queries[37] (698576c5-c250-43ed-94d9-3b1613e909d1)
INFO:buildstock_query.query_core:Submitted queries[38] (7bbd5a2c-6510-4101-83cc-25c0d7781d2c)
INFO:buildstock_query.query_core:{'submitted': 39, 'running': 3, 'pending': 23, 'completed': 32, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[39] (e9bd74a8-5e70-4625-b50b-77942aca2613)
INFO:buildstock_query.query_core:{'submitted': 40, 'running': 4, 'pending': 22, 'completed': 32, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 40, 'running': 4, 'pending': 22, 'completed': 32, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 40, 'running': 4, 'pending': 22, 'completed': 32, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[40] (4e61345d-20ab-452f-abc0-968216e6b161)
INFO:buildstock_query.query_core:Submitted queries[41] (64cbd39c-425a-48cf-9efd-26ce4306f629)
INFO:buildstock_query.query_core:Submitted queries[42] (07c90c13-177a-4b35-83cd-97dae1ca4225)
INFO:buildstock_query.query_core:Submitted queries[43] (9e3307ef-306b-4889-a498-7e18953137b7)
INFO:buildstock_query.query_core:{'submitted': 44, 'running': 4, 'pending': 18, 'completed': 36, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 44, 'running': 4, 'pending': 18, 'completed': 36, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 44, 'running': 4, 'pending': 18, 'completed': 36, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[44] (1e4fe6d4-fa34-42b5-b362-b9dd7c161de6)
INFO:buildstock_query.query_core:Submitted queries[45] (d0972fb9-0d81-4d41-a8ca-9d42b1759bb0)
INFO:buildstock_query.query_core:{'submitted': 46, 'running': 2, 'pending': 16, 'completed': 40, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[46] (fc5bdb5d-6acf-44ab-98a6-567df7864652)
INFO:buildstock_query.query_core:Submitted queries[47] (e2e3d99f-5b57-4299-a676-899678c8f436)
INFO:buildstock_query.query_core:{'submitted': 48, 'running': 4, 'pending': 14, 'completed': 40, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 48, 'running': 4, 'pending': 14, 'completed': 40, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 48, 'running': 4, 'pending': 14, 'completed': 40, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[48] (d2ff888d-4e51-4f38-b248-df827d5e651d)
INFO:buildstock_query.query_core:Submitted queries[49] (7a51785c-4ec4-4f3b-b878-4dc4be91b961)
INFO:buildstock_query.query_core:Submitted queries[50] (f0351700-32a1-4714-8089-a476b1380ca7)
INFO:buildstock_query.query_core:Submitted queries[51] (2a7ac8d2-fbe6-4d98-9220-5038c08586a8)
INFO:buildstock_query.query_core:{'submitted': 52, 'running': 4, 'pending': 10, 'completed': 44, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 52, 'running': 4, 'pending': 10, 'completed': 44, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 52, 'running': 4, 'pending': 10, 'completed': 44, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[52] (8bff24ce-e004-4a87-95fa-23c5c4f17522)
INFO:buildstock_query.query_core:Submitted queries[53] (fd7dc3ca-1489-43c7-9910-542d9a431127)
INFO:buildstock_query.query_core:Submitted queries[54] (5d7cbb90-94d0-4c65-a89b-34b2697deae8)
INFO:buildstock_query.query_core:Submitted queries[55] (3e955bf8-dd93-4e5d-b86d-b11e1d27371b)
INFO:buildstock_query.query_core:{'submitted': 56, 'running': 4, 'pending': 6, 'completed': 48, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 56, 'running': 4, 'pending': 6, 'completed': 48, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 56, 'running': 4, 'pending': 6, 'completed': 48, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 56, 'running': 4, 'pending': 6, 'completed': 48, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[56] (f2618154-4d63-4313-bd3f-959e421b6daf)
INFO:buildstock_query.query_core:Submitted queries[57] (d1cde07b-6fcf-4116-9010-5b0599098885)
INFO:buildstock_query.query_core:Submitted queries[58] (1aa71c9a-8313-460a-88eb-ba8863132bed)
INFO:buildstock_query.query_core:Submitted queries[59] (341e69fc-7713-4960-a1b3-81621087edc3)
INFO:buildstock_query.query_core:{'submitted': 60, 'running': 4, 'pending': 2, 'completed': 52, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 60, 'running': 4, 'pending': 2, 'completed': 52, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 60, 'running': 4, 'pending': 2, 'completed': 52, 'failed': 4}
INFO:buildstock_query.query_core:Submitted queries[60] (996331c7-ec2b-4028-9725-34d319843f2c)
INFO:buildstock_query.query_core:Submitted queries[61] (f82d858b-a992-4174-813a-9ba24c0c1c4c)
INFO:buildstock_query.query_core:{'submitted': 62, 'running': 2, 'pending': 0, 'completed': 56, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 62, 'running': 1, 'pending': 0, 'completed': 57, 'failed': 4}
INFO:buildstock_query.query_core:{'submitted': 62, 'running': 0, 'pending': 0, 'completed': 58, 'failed': 4}
INFO:buildstock_query.query_core:Batch query completed.
WARNING:buildstock_query.query_core:4 queries failed. Redoing them
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 4, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 4, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[0] (94013219-8373-4cf2-be54-88a0b9bc15cb)
INFO:buildstock_query.query_core:Submitted queries[1] (f2f5918f-4b38-44bc-812f-96190c3fa7ae)
INFO:buildstock_query.query_core:Submitted queries[2] (ad27c2ce-0f8f-4b9d-addd-c1673827707b)
INFO:buildstock_query.query_core:Submitted queries[3] (9c32f5fd-8b1b-4190-98ca-ce733da846d2)
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 0, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 0, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 0, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 4, 'pending': 0, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 3, 'pending': 0, 'completed': 1, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 0, 'pending': 0, 'completed': 4, 'failed': 0}
INFO:buildstock_query.query_core:The queries succeeded this time. Gathering all the results.
INFO:buildstock_query.query_core:Got result from Query [0] (f8ad1c66-5428-48bd-b842-d149dbb72a2c)
INFO:buildstock_query.query_core:f8ad1c66-5428-48bd-b842-d149dbb72a2c cost 0.0 GB ($0.0). Session total: 0.0 GB ($0.0)
INFO:buildstock_query.query_core:Got result from Query [1] (04d50590-1ec5-4dbf-ac3b-4eb355e6fd26)
INFO:buildstock_query.query_core:04d50590-1ec5-4dbf-ac3b-4eb355e6fd26 cost 0.0 GB ($0.0). Session total: 0.0 GB ($0.0)
INFO:buildstock_query.query_core:Got result from Query [2] (ea408670-b2ec-4613-b9fe-440b83cf7f40)
INFO:buildstock_query.query_core:ea408670-b2ec-4613-b9fe-440b83cf7f40 cost 0.0 GB ($0.0). Session total: 0.0 GB ($0.0)

QueryException: [ErrorCode: INTERNAL_ERROR_QUERY_ENGINE] Amazon Athena experienced an internal error while executing this query. Please contact AWS support for further assistance. You will not be charged for this query. We apologize for the inconvenience.

In [20]:
hvac_columns = [
"out.electricity.heating.energy_consumption",
"out.electricity.cooling.energy_consumption",
"out.electricity.fans.energy_consumption",
"out.electricity.heat_recovery.energy_consumption",
"out.electricity.heat_rejection.energy_consumption",
"out.electricity.pumps.energy_consumption"
]

non_hvac_columns = [
    "out.electricity.exterior_lighting.energy_consumption",
    "out.electricity.interior_lighting.energy_consumption",
    "out.electricity.interior_equipment.energy_consumption",
    "out.electricity.refrigeration.energy_consumption",
    "out.electricity.water_systems.energy_consumption",
]
#computed_col_expr = "out.electricity.total.energy_consumption - " + " - ".join(hvac_columns)
computed_col_expr = " + ".join(non_hvac_columns)
non_hvac_load = my_run.get_calculated_column("out.electricity.non_hvac_load.energy_consumption", computed_col_expr,
                                             table='timeseries')

# for upgrade in [0, 1, 14, 55, 59]:

sqft_col = my_run._get_enduse_cols(["in.sqft"], table="baseline")[0]


for upgrade in [1]:
    print(f"Running for upgrade {upgrade}...")
    agg_df = my_run.query(enduses=[sqft_col, non_hvac_load], annual_only=False,
                                timestamp_grouping_func="hour", group_by=["state"],
                                get_query_only=False, upgrade_id=upgrade)
    agg_df.sort_values(["state", "timestamp"], inplace=True)
    agg_df.to_csv(f"comstock_amy2018_r2_2025_ts_aggregates_upgrade_{upgrade}_2026mar17_directsum.csv", index=False)

Running for upgrade 1...

/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING

KeyboardInterrupt:

In [11]:
df = pd.read_csv("/Users/radhikar/Documents/buildstock2025/weather normalization/buildstock-weatherreg/aggregates/comstock_amy2018_r2_2025_ts_aggregates_upgrade_0_2026mar11.csv")
df

,timestamp,state,sample_count,units_count,rows_per_sample,electricity.non_hvac_load.energy_consumption
0,2018-01-01 00:00:00,AK,1421,8113.081188,4,98676.592808
1,2018-01-01 01:00:00,AK,1421,8113.081188,4,92504.952760
2,2018-01-01 02:00:00,AK,1421,8113.081188,4,87315.168164
3,2018-01-01 03:00:00,AK,1421,8113.081188,4,83004.743818
4,2018-01-01 04:00:00,AK,1421,8113.081188,4,79747.243988
...,...,...,...,...,...,...
446755,2018-12-31 19:00:00,WY,1715,29465.961907,6,348948.166631
446756,2018-12-31 20:00:00,WY,1715,29465.961907,6,323732.133939
446757,2018-12-31 21:00:00,WY,1715,29465.961907,6,296967.410004
446758,2018-12-31 22:00:00,WY,1715,29465.961907,6,277117.880650
446759,2018-12-31 23:00:00,WY,1715,29465.961907,6,258439.644538

In [12]:
df.groupby("timestamp").agg({"electricity.non_hvac_load.energy_consumption":"sum"})

                     electricity.non_hvac_load.energy_consumption
timestamp
2018-01-01 00:00:00                                  8.607200e+07
2018-01-01 01:00:00                                  8.024530e+07
2018-01-01 02:00:00                                  7.579861e+07
2018-01-01 03:00:00                                  7.406878e+07
2018-01-01 04:00:00                                  7.518976e+07
...                                                           ...
2018-12-31 19:00:00                                  1.206556e+08
2018-12-31 20:00:00                                  1.120993e+08
2018-12-31 21:00:00                                  1.039414e+08
2018-12-31 22:00:00                                  9.692070e+07
2018-12-31 23:00:00                                  9.102532e+07

[8760 rows x 1 columns]

In [ ]:
agg_df

,timestamp,state,sample_count,units_count,rows_per_sample,electricity.non_hvac_load.energy_consumption
192247,2018-01-01 00:00:00,AK,1421,8113.081188,4,1.075611e+05
192298,2018-01-01 01:00:00,AK,1421,8113.081188,4,1.010559e+05
192349,2018-01-01 02:00:00,AK,1421,8113.081188,4,9.545638e+04
192400,2018-01-01 03:00:00,AK,1421,8113.081188,4,9.093217e+04
192451,2018-01-01 04:00:00,AK,1421,8113.081188,4,8.810727e+04
...,...,...,...,...,...,...
306739,2018-12-31 19:00:00,WY,1715,51259.847982,58,5.272866e+06
306790,2018-12-31 20:00:00,WY,1715,51259.847982,58,4.897796e+06
306841,2018-12-31 21:00:00,WY,1715,51259.847982,58,4.516881e+06
306892,2018-12-31 22:00:00,WY,1715,51259.847982,58,4.253574e+06
306943,2018-12-31 23:00:00,WY,1715,51259.847982,58,3.949455e+06

In [ ]:
agg_df.sort_values(["state", "timestamp"], inplace=True)
agg_df.to_csv("resstock_aggregates_upgrade_0.csv", index=False)

In [ ]:
agg_df

,timestamp,state,sample_count,units_count,rows_per_sample,total_except_ev
52431,2018-01-01 00:00:00,AK,1255,318649.109273,4,7.571812e+09
52482,2018-01-01 01:00:00,AK,1255,318649.109273,4,7.571812e+09
52533,2018-01-01 02:00:00,AK,1255,318649.109273,4,7.571812e+09
52584,2018-01-01 03:00:00,AK,1255,318649.109273,4,7.571812e+09
52635,2018-01-01 04:00:00,AK,1255,318649.109273,4,7.571812e+09
...,...,...,...,...,...,...
149446,2018-12-31 19:00:00,WY,1101,279547.943673,4,1.149700e+10
149497,2018-12-31 20:00:00,WY,1101,279547.943673,4,1.149700e+10
149548,2018-12-31 21:00:00,WY,1101,279547.943673,4,1.149700e+10
149599,2018-12-31 22:00:00,WY,1101,279547.943673,4,1.149700e+10
149650,2018-12-31 23:00:00,WY,1101,279547.943673,4,1.149700e+10

In [6]:
my_run.save_cache()

INFO:buildstock_query.query_core:11 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl

In [7]:
all_enduses = my_run.get_cols(my_run.ts_table)
all_enduses

[Column('time', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('timedst', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('timeutc', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('districtcooling_cooling_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('districtheating_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('districtheating_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_cooling_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_elevators_interior_equipment_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_exterior_lighting_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_fans_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heat_recovery_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heat_rejection_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heating_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_interior_equipment_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_interior_lighting_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_pumps_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_refrigeration_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_water_systems_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('fueloil_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('fueloil_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_interior_equipment_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('heat_rejection_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('propane_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('propane_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_districtcooling_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_districtheating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_electricity_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_fueloil_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_gas_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_propane_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_water_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('water_systems_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('building_id', BIGINT(), table=<chiller_v3_timeseries>),
 Column('upgrade', String(), table=<chiller_v3_timeseries>)]

In [9]:
ts_agg = my_run.query(enduses=['electricity_heating_kwh'],
                                         # restrict=[('build_existing_model.state', ['CO'])],
                                         timestamp_grouping_func='month',
                                         group_by=['changebuildinglocation_climate_zone'],
                                         annual_only=False,
                                         get_query_only=False)
print(ts_agg)

          time changebuildinglocation_climate_zone  sample_count units_count  \
0   2018-01-01                  ASHRAE 169-2013-1A           362         362
1   2018-01-01                  ASHRAE 169-2013-2A           721         721
2   2018-01-01                  ASHRAE 169-2013-2B           355         355
3   2018-01-01                  ASHRAE 169-2013-3A          1271        1271
4   2018-01-01                  ASHRAE 169-2013-3B           365         365
..         ...                                 ...           ...         ...
355 2018-12-01                            T24-CEC5            94          94
356 2018-12-01                            T24-CEC6            22          22
357 2018-12-01                            T24-CEC7           143         143
358 2018-12-01                            T24-CEC8           167         167
359 2018-12-01                            T24-CEC9           163         163

    rows_per_sample  electricity_heating_kwh
0              2976             1.874540e+05
1              2976             7.236298e+06
2              2976             1.990981e+06
3              2976             2.879234e+07
4              2976             2.188927e+06
..              ...                      ...
355            2976             1.305064e+06
356            2976             1.378554e+05
357            2976             1.495813e+06
358            2976             1.262215e+06
359            2976             2.673578e+06

[360 rows x 6 columns]

In [10]:
result = my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             annual_only=False,
                             include_savings=True,
                             include_baseline=True,
                             include_upgrade=True,
                             get_query_only=False)
print(result)

                     time  sample_count  units_count  \
0     2018-01-01 00:15:00         10476        10476
1     2018-01-01 00:30:00         10476        10476
2     2018-01-01 00:45:00         10476        10476
3     2018-01-01 01:00:00         10476        10476
4     2018-01-01 01:15:00         10476        10476
...                   ...           ...          ...
35035 2018-12-31 23:00:00         10476        10476
35036 2018-12-31 23:15:00         10476        10476
35037 2018-12-31 23:30:00         10476        10476
35038 2018-12-31 23:45:00         10476        10476
35039 2019-01-01 00:00:00         10476        10476

       electricity_heating_kwh__baseline  electricity_heating_kwh__upgrade  \
0                          148097.855523                     146644.923577
1                          150639.973940                     149161.628578
2                          153675.436235                     152326.288008
3                          156372.755189                     155042.306053
4                          155214.387546                     153924.114566
...                                  ...                               ...
35035                       67071.615089                      66464.315870
35036                       66447.071670                      65819.072259
35037                       66809.981943                      66203.432928
35038                       67397.005424                      66876.495433
35039                       69087.741211                      68695.955151

       electricity_heating_kwh__savings
0                           1452.931946
1                           1478.345362
2                           1349.148227
3                           1330.449136
4                           1290.272980
...                                 ...
35035                        607.299218
35036                        627.999411
35037                        606.549015
35038                        520.509991
35039                        391.786060

[35040 rows x 6 columns]

In [11]:
my_run.save_cache()

INFO:buildstock_query.query_core:15 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl

In [12]:
my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             group_by=['changebuildinglocation_climate_zone'],
                             annual_only=False,
                             include_savings=True,
                             include_baseline=False,
                             include_upgrade=False,
                             get_query_only=False)

INFO:pyathena.pandas.result_set:Reading 79453434 bytes from S3 in full mode using python engine

,time,sample_count,units_count,electricity_heating_kwh__savings,changebuildinglocation_climate_zone
0,2018-01-01 00:15:00,362,362,0.349747,ASHRAE 169-2013-1A
1,2018-01-01 00:30:00,362,362,0.239264,ASHRAE 169-2013-1A
2,2018-01-01 00:45:00,362,362,-0.001893,ASHRAE 169-2013-1A
3,2018-01-01 01:00:00,362,362,0.125232,ASHRAE 169-2013-1A
4,2018-01-01 01:15:00,362,362,-0.005029,ASHRAE 169-2013-1A
...,...,...,...,...,...
1051195,2018-12-31 23:00:00,130,130,0.473219,T24-CEC9
1051196,2018-12-31 23:15:00,130,130,0.455798,T24-CEC9
1051197,2018-12-31 23:30:00,130,130,0.442982,T24-CEC9
1051198,2018-12-31 23:45:00,130,130,0.425980,T24-CEC9
1051199,2019-01-01 00:00:00,130,130,0.419135,T24-CEC9

In [13]:
result = my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             group_by=['changebuildinglocation_climate_zone'],
                             #restrict=[('in.state', ['VT'])],
                             get_quartiles=True,
                             annual_only=True,
                             include_savings=True,
                             get_query_only=False)
print(result)

    sample_count  units_count  electricity_heating_kwh__upgrade  \
0            173          173                      4.071361e+05
1            115          115                      1.273817e+06
2             92           92                      2.546142e+06
3            438          438                      2.435752e+07
4             64           64                      2.461850e+06
5            308          308                      2.399288e+07
6            110          110                      5.817347e+06
7             20           20                      1.430656e+06
8            454          454                      1.028741e+08
9            112          112                      1.031718e+07
10           238          238                      3.650869e+07
11            25           25                      4.286214e+06
12           120          120                      1.953001e+07
13            22           22                      4.219544e+06
14             3            3                      2.880556e+03
15            40           40                      4.931531e+06
16             2            2                      4.166250e+05
17            22           22                      1.467344e+06
18            20           20                      2.536114e+06
19            46           46                      2.781519e+06
20             1            1                      3.072222e+03
21            29           29                      1.278717e+06
22            13           13                      7.069944e+05
23            30           30                      6.822861e+05
24             3            3                      9.816667e+03
25             5            5                      1.360361e+05
26            41           41                      1.469039e+06
27            48           48                      2.347439e+06

    electricity_heating_kwh__savings  \
0                         433.333333
1                       40550.000000
2                       14588.888889
3                      639897.222222
4                        -180.555556
5                      274761.111111
6                       -1158.333333
7                        3727.777778
8                      136188.888889
9                       13472.222222
10                      39483.333333
11                       4727.777778
12                       9519.444444
13                      -2311.111111
14                          0.000000
15                       -808.333333
16                          0.000000
17                       -252.777778
18                         25.000000
19                       -902.777778
20                          5.555556
21                       -205.555556
22                       -411.111111
23                         77.777778
24                          0.000000
25                          0.000000
26                       -100.000000
27                       5402.777778

          electricity_heating_kwh__upgrade__quartiles  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 5.8184523809523805, ...
1   [0.0, 0.0, 0.0, 0.0, 300.42438271604937, 12561...
2   [0.0, 0.0, 0.0, 0.0, 620.4444444444445, 18945....
3   [0.0, 0.0, 0.0, 0.0, 1494.3162584627635, 50923...
4   [0.0, 0.0, 0.0, 0.0, 5326.080246913581, 37092....
5   [0.0, 0.0, 0.0, 0.0, 1031.7145376669187, 64079...
6   [0.0, 0.0, 0.0, 0.0, 1149.9228395061727, 55582...
7   [0.0, 0.0, 0.0, 0.0, 10341.666666666666, 93488...
8   [0.0, 0.0, 0.0, 0.0, 28401.730690745848, 27332...
9   [0.0, 0.0, 0.0, 0.0, 494.75308641975306, 54290...
10  [0.0, 0.0, 0.0, 0.0, 18091.16188769415, 176736...
11  [0.0, 0.0, 0.0, 0.0, 16516.666666666668, 14069...
12  [0.0, 0.0, 0.0, 0.0, 38395.833333333336, 22901...
13  [0.0, 0.0, 0.0, 0.0, 11050.0, 423625.0, 550000...
14  [0.0, 0.0, 0.0, 0.0, 791.6666666666666, 2088.8...
15  [0.0, 0.0, 0.0, 0.0, 1817.3611111111113, 52300...
16  [10736.111111111111, 10736.111111111111, 10736...
17  [0.0, 0.0, 0.0, 0.0, 12305.555555555557, 53366...
18  [0.0, 0.0, 0.0, 0.0, 4691.666666666667, 314138...
19  [0.0, 0.0, 0.0, 0.0, 912.5, 17455.555555555555...
20  [3072.222222222222, 3072.222222222222, 3072.22...
21  [0.0, 0.0, 0.0, 0.0, 1933.3333333333333, 47794...
22  [0.0, 0.0, 0.0, 0.0, 0.0, 19463.888888888887, ...
23  [0.0, 0.0, 0.0, 0.0, 0.0, 6180.555555555556, 1...
24  [0.0, 0.0, 0.0, 0.0, 0.0, 9816.666666666666, 9...
25  [0.0, 0.0, 0.0, 0.0, 0.0, 4277.777777777778, 1...
26  [0.0, 0.0, 0.0, 0.0, 13.194444444444446, 6452....
27  [0.0, 0.0, 0.0, 0.0, 2114.583333333333, 57019....

          electricity_heating_kwh__savings__quartiles  \
0   [-52.77777777777828, -2.7777777777777786, 0.0,...
1   [-158.33333333333348, -2.7777777777773736, 0.0...
2   [-602.7777777777778, -177.77777777777737, 0.0,...
3   [-2391.666666666667, -461.4722222222223, 0.0, ...
4   [-205.55555555555475, -175.0, 0.0, 0.0, 0.0, 0...
5   [-2902.777777777778, -655.5555555555555, -0.76...
6   [-4525.000000000007, -241.66666666666669, 0.0,...
7   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 736.11111111110...
8   [-21577.77777777787, -625.444444444445, 0.0, 0...
9   [-602.7777777777737, -258.33333333333337, 0.0,...
10  [-752.7777777777777, -313.88888888888687, 0.0,...
11  [-13.888888888890506, -13.888888888890506, 0.0...
12  [-263.88888888888886, -13.888888888888893, 0.0...
13  [-5444.444444444444, -5444.444444444444, -286....
14      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
15  [-1183.3333333333333, -1183.3333333333333, 0.0...
16      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
17  [-144.44444444443798, -144.44444444443798, 0.0...
18  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.7777777777773...
19  [-1322.2222222222222, -1322.2222222222222, 0.0...
20  [5.555555555555657, 5.555555555555657, 5.55555...
21  [-150.0, -150.0, -13.88888888888889, 0.0, 0.0,...
22  [-425.0, -425.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.8...
23  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 77.7777777...
24      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
25      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
26  [-66.66666666666667, -66.66666666666667, 0.0, ...
27  [-836.1111111111111, -836.1111111111111, -27.7...

   changebuildinglocation_climate_zone
0                   ASHRAE 169-2013-1A
1                   ASHRAE 169-2013-2A
2                   ASHRAE 169-2013-2B
3                   ASHRAE 169-2013-3A
4                   ASHRAE 169-2013-3B
5                   ASHRAE 169-2013-4A
6                   ASHRAE 169-2013-4B
7                   ASHRAE 169-2013-4C
8                   ASHRAE 169-2013-5A
9                   ASHRAE 169-2013-5B
10                  ASHRAE 169-2013-6A
11                  ASHRAE 169-2013-6B
12                  ASHRAE 169-2013-7A
13                  ASHRAE 169-2013-8A
14                            T24-CEC1
15                           T24-CEC10
16                           T24-CEC11
17                           T24-CEC12
18                           T24-CEC13
19                           T24-CEC14
20                           T24-CEC15
21                           T24-CEC16
22                            T24-CEC3
23                            T24-CEC5
24                            T24-CEC6
25                            T24-CEC7
26                            T24-CEC8
27                            T24-CEC9

In [14]:
my_run.save_cache()

INFO:buildstock_query.query_core:17 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl