In [2]:
from buildstock_query import BuildStockQuery
import pandas as pd

In [3]:
# autoreload
%load_ext autoreload
%autoreload 2

In [10]:
my_run = BuildStockQuery('ghpphase2','buildstock_sdr',
                         ("resstock_amy2018_r1_2025_md_national_vu",
                          "resstock_amy2018_r1_2025_ts_by_state_vu",
                          "resstock_amy2018_r1_2025_md_national_vu"),
                        buildstock_type='resstock',
                        db_schema="resstock_oedi",
                        skip_reports=False)

INFO:buildstock_query.query_core:Loading ('resstock_amy2018_r1_2025_md_national_vu', 'resstock_amy2018_r1_2025_ts_by_state_vu', 'resstock_amy2018_r1_2025_md_national_vu') ...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:buildstock_query.main:Getting Success counts...
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
INFO:botocore.tokens:Loading cached SSO token for nrel-sso
/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)
INFO:buildstock_query.report_query:Checking integrity with ts_tables ...
/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 33, 'completed': 0, 'failed': 0}

          success  inapplicable  fail       Sum  Applied %  no-chng  bad-chng  \
upgrade
0        549971.0           0.0     0  549971.0        0.0      0.0       0.0
1        408800.0      141171.0     0  549971.0       74.3      0.0       0.0
10       306290.0      243681.0     0  549971.0       55.7      0.0       0.0
11       507164.0       42807.0     0  549971.0       92.2      0.0       0.0
12       235984.0      313987.0     0  549971.0       42.9      0.0       0.0
13       255778.0      294193.0     0  549971.0       46.5      0.0       0.0
14       510174.0       39797.0     0  549971.0       92.8      0.0       0.0
15       538285.0       11686.0     0  549971.0       97.9      0.0       0.0
16       539123.0       10848.0     0  549971.0       98.0      0.0       0.0
17       549971.0           0.0     0  549971.0      100.0      0.0       0.0
18       388830.0      161141.0     0  549971.0       70.7      0.0       0.0
19       477548.0       72423.0     0  549971.0       86.8      0.0       0.0
2         31876.0      518095.0     0  549971.0        5.8      0.0       0.0
20       483326.0       66645.0     0  549971.0       87.9      0.0       0.0
21       483326.0       66645.0     0  549971.0       87.9      0.0       0.0
22       483327.0       66644.0     0  549971.0       87.9      0.0       0.0
23       483327.0       66644.0     0  549971.0       87.9      0.0       0.0
24       548254.0        1717.0     0  549971.0       99.7      0.0       0.0
25       548255.0        1716.0     0  549971.0       99.7      0.0       0.0
26       548254.0        1717.0     0  549971.0       99.7      0.0       0.0
27       548255.0        1716.0     0  549971.0       99.7      0.0       0.0
28       548256.0        1715.0     0  549971.0       99.7      0.0       0.0
29       427034.0      122924.0     0  549958.0       77.6      0.0       0.0
3        413611.0      136360.0     0  549971.0       75.2      0.0       0.0
30       508537.0       41421.0     0  549958.0       92.5      0.0       0.0
31       388825.0      161133.0     0  549958.0       70.7      0.0       0.0
32       388815.0      161143.0     0  549958.0       70.7      0.0       0.0
4        413604.0      136367.0     0  549971.0       75.2      0.0       0.0
5        245570.0      304401.0     0  549971.0       44.7      0.0       0.0
6        388823.0      161148.0     0  549971.0       70.7      0.0       0.0
7        388822.0      161149.0     0  549971.0       70.7      0.0       0.0
8        386746.0      163225.0     0  549971.0       70.3      0.0       0.0
9        546822.0        3149.0     0  549971.0       99.4      0.0       0.0

         ok-chng  true-bad-chng  true-ok-chng  null  any  no-chng %  \
upgrade
0            0.0            0.0           0.0   0.0  0.0        0.0
1            0.0            0.0           0.0   0.0  0.0        0.0
10           0.0            0.0           0.0   0.0  0.0        0.0
11           0.0            0.0           0.0   0.0  0.0        0.0
12           0.0            0.0           0.0   0.0  0.0        0.0
13           0.0            0.0           0.0   0.0  0.0        0.0
14           0.0            0.0           0.0   0.0  0.0        0.0
15           0.0            0.0           0.0   0.0  0.0        0.0
16           0.0            0.0           0.0   0.0  0.0        0.0
17           0.0            0.0           0.0   0.0  0.0        0.0
18           0.0            0.0           0.0   0.0  0.0        0.0
19           0.0            0.0           0.0   0.0  0.0        0.0
2            0.0            0.0           0.0   0.0  0.0        0.0
20           0.0            0.0           0.0   0.0  0.0        0.0
21           0.0            0.0           0.0   0.0  0.0        0.0
22           0.0            0.0           0.0   0.0  0.0        0.0
23           0.0            0.0           0.0   0.0  0.0        0.0
24           0.0            0.0           0.0   0.0  0.0        0.0
25           0.0            0.0           0.0   0.0  0.0        0.0
26           0.0            0.0           0.0   0.0  0.0        0.0
27           0.0            0.0           0.0   0.0  0.0        0.0
28           0.0            0.0           0.0   0.0  0.0        0.0
29           0.0            0.0           0.0   0.0  0.0        0.0
3            0.0            0.0           0.0   0.0  0.0        0.0
30           0.0            0.0           0.0   0.0  0.0        0.0
31           0.0            0.0           0.0   0.0  0.0        0.0
32           0.0            0.0           0.0   0.0  0.0        0.0
4            0.0            0.0           0.0   0.0  0.0        0.0
5            0.0            0.0           0.0   0.0  0.0        0.0
6            0.0            0.0           0.0   0.0  0.0        0.0
7            0.0            0.0           0.0   0.0  0.0        0.0
8            0.0            0.0           0.0   0.0  0.0        0.0
9            0.0            0.0           0.0   0.0  0.0        0.0

         bad-chng %  ok-chng %  true-ok-chng %  true-bad-chng %
upgrade
0               0.0        0.0             0.0              0.0
1               0.0        0.0             0.0              0.0
10              0.0        0.0             0.0              0.0
11              0.0        0.0             0.0              0.0
12              0.0        0.0             0.0              0.0
13              0.0        0.0             0.0              0.0
14              0.0        0.0             0.0              0.0
15              0.0        0.0             0.0              0.0
16              0.0        0.0             0.0              0.0
17              0.0        0.0             0.0              0.0
18              0.0        0.0             0.0              0.0
19              0.0        0.0             0.0              0.0
2               0.0        0.0             0.0              0.0
20              0.0        0.0             0.0              0.0
21              0.0        0.0             0.0              0.0
22              0.0        0.0             0.0              0.0
23              0.0        0.0             0.0              0.0
24              0.0        0.0             0.0              0.0
25              0.0        0.0             0.0              0.0
26              0.0        0.0             0.0              0.0
27              0.0        0.0             0.0              0.0
28              0.0        0.0             0.0              0.0
29              0.0        0.0             0.0              0.0
3               0.0        0.0             0.0              0.0
30              0.0        0.0             0.0              0.0
31              0.0        0.0             0.0              0.0
32              0.0        0.0             0.0              0.0
4               0.0        0.0             0.0              0.0
5               0.0        0.0             0.0              0.0
6               0.0        0.0             0.0              0.0
7               0.0        0.0             0.0              0.0
8               0.0        0.0             0.0              0.0
9               0.0        0.0             0.0              0.0

INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 33, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:{'submitted': 0, 'running': 0, 'pending': 33, 'completed': 0, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[0] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[1] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 2, 'running': 0, 'pending': 31, 'completed': 2, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[2] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[3] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 4, 'running': 0, 'pending': 29, 'completed': 4, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[4] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[5] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[6] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[7] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[8] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 9, 'running': 0, 'pending': 24, 'completed': 9, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[9] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[10] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[11] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[12] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[13] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[14] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[15] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[16] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[17] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 18, 'running': 0, 'pending': 15, 'completed': 18, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[18] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[19] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[20] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[21] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[22] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[23] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[24] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[25] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[26] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[27] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[28] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[29] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 30, 'running': 0, 'pending': 3, 'completed': 30, 'failed': 0}
INFO:buildstock_query.query_core:Submitted queries[30] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[31] (CACHED)
INFO:buildstock_query.query_core:Submitted queries[32] (CACHED)
INFO:buildstock_query.query_core:{'submitted': 33, 'running': 0, 'pending': 0, 'completed': 33, 'failed': 0}
INFO:buildstock_query.query_core:Batch query completed.
INFO:buildstock_query.query_core:Got result from Query [0] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [1] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [2] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [3] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [4] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [5] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [6] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [7] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [8] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [9] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [10] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [11] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [12] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [13] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [14] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [15] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [16] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [17] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [18] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [19] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [20] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [21] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [22] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [23] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [24] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [25] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [26] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [27] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [28] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [29] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [30] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [31] (CACHED)
INFO:buildstock_query.query_core:Got result from Query [32] (CACHED)
INFO:buildstock_query.query_core:Concatenating the results.
/Users/radhikar/Documents/buildstock2025/buildstock-query-applied_only/buildstock_query/report_query.py:95: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  change_df = change_df.fillna(0)

Upgrade 29 has 0 samples in timeseries table, but 549967.0 samples in baseline/upgrade table.
Upgrade 30 has 0 samples in timeseries table, but 549967.0 samples in baseline/upgrade table.
Upgrade 31 has 0 samples in timeseries table, but 549967.0 samples in baseline/upgrade table.
Upgrade 32 has 0 samples in timeseries table, but 549967.0 samples in baseline/upgrade table.

INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING
INFO:buildstock_query.query_core:Query is RUNNING

TimeoutError: Query failed to complete within 30 mins.

In [5]:
hvac_columns = [
"out.electricity.heating.energy_consumption",
"out.electricity.heating_fans_pumps.energy_consumption",
"out.electricity.heating_hp_bkup.energy_consumption",
"out.electricity.heating_hp_bkup_fa.energy_consumption",
"out.electricity.cooling.energy_consumption",
"out.electricity.cooling_fans_pumps.energy_consumption"
]
excluded_columns = [*hvac_columns, "out.electricity.ev_charging.energy_consumption"]
computed_col_expr = "out.electricity.total.energy_consumption - " + " - ".join(excluded_columns)
computed_col_expr

'out.electricity.total.energy_consumption - out.electricity.heating.energy_consumption - out.electricity.heating_fans_pumps.energy_consumption - out.electricity.heating_hp_bkup.energy_consumption - out.electricity.heating_hp_bkup_fa.energy_consumption - out.electricity.cooling.energy_consumption - out.electricity.cooling_fans_pumps.energy_consumption - out.electricity.ev_charging.energy_consumption'

In [ ]:
hvac_columns = [
"out.electricity.heating.energy_consumption",
"out.electricity.heating_fans_pumps.energy_consumption",
"out.electricity.heating_hp_bkup.energy_consumption",
"out.electricity.heating_hp_bkup_fa.energy_consumption",
"out.electricity.cooling.energy_consumption",
"out.electricity.cooling_fans_pumps.energy_consumption"
]
excluded_columns = [*hvac_columns, "out.electricity.ev_charging.energy_consumption"]
computed_col_expr = "out.electricity.total.energy_consumption - " + " - ".join(excluded_columns)
all_except_pv_and_ev = my_run.get_calculated_column("out.electricity.non_hvac_load.energy_consumption", computed_col_expr,
table='timeseries')
for upgrade in [0, 4, 8]:

    print(f"Running for upgrade {upgrade}...")
    agg_df = my_run.query(enduses=[all_except_pv_and_ev], annual_only=False,
                                timestamp_grouping_func="hour", group_by=["state"],
                                get_query_only=False, upgrade_id=upgrade)
    agg_df.sort_values(["state", "timestamp"], inplace=True)
    agg_df.to_csv(f"resstock_amy2018_r1_2025_upgrade_{upgrade}_2026mar11.csv", index=False)

In [9]:
agg_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
agg_df.sort_values(["state", "timestamp"], inplace=True)
agg_df.to_csv("resstock_aggregates_upgrade_0.csv", index=False)

In [ ]:
agg_df

,timestamp,state,sample_count,units_count,rows_per_sample,total_except_ev
52431,2018-01-01 00:00:00,AK,1255,318649.109273,4,7.571812e+09
52482,2018-01-01 01:00:00,AK,1255,318649.109273,4,7.571812e+09
52533,2018-01-01 02:00:00,AK,1255,318649.109273,4,7.571812e+09
52584,2018-01-01 03:00:00,AK,1255,318649.109273,4,7.571812e+09
52635,2018-01-01 04:00:00,AK,1255,318649.109273,4,7.571812e+09
...,...,...,...,...,...,...
149446,2018-12-31 19:00:00,WY,1101,279547.943673,4,1.149700e+10
149497,2018-12-31 20:00:00,WY,1101,279547.943673,4,1.149700e+10
149548,2018-12-31 21:00:00,WY,1101,279547.943673,4,1.149700e+10
149599,2018-12-31 22:00:00,WY,1101,279547.943673,4,1.149700e+10
149650,2018-12-31 23:00:00,WY,1101,279547.943673,4,1.149700e+10

In [6]:
my_run.save_cache()

INFO:buildstock_query.query_core:11 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl

In [7]:
all_enduses = my_run.get_cols(my_run.ts_table)
all_enduses

[Column('time', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('timedst', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('timeutc', TIMESTAMP(), table=<chiller_v3_timeseries>),
 Column('districtcooling_cooling_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('districtheating_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('districtheating_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_cooling_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_elevators_interior_equipment_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_exterior_lighting_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_fans_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heat_recovery_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heat_rejection_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_heating_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_interior_equipment_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_interior_lighting_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_pumps_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_refrigeration_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('electricity_water_systems_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('fueloil_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('fueloil_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_interior_equipment_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('gas_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('heat_rejection_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('propane_heating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('propane_water_systems_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_districtcooling_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_districtheating_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_electricity_kwh', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_fueloil_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_gas_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_propane_kbtu', FLOAT(), table=<chiller_v3_timeseries>),
 Column('total_site_water_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('water_systems_gal', FLOAT(), table=<chiller_v3_timeseries>),
 Column('building_id', BIGINT(), table=<chiller_v3_timeseries>),
 Column('upgrade', String(), table=<chiller_v3_timeseries>)]

In [9]:
ts_agg = my_run.query(enduses=['electricity_heating_kwh'],
                                         # restrict=[('build_existing_model.state', ['CO'])],
                                         timestamp_grouping_func='month',
                                         group_by=['changebuildinglocation_climate_zone'],
                                         annual_only=False,
                                         get_query_only=False)
print(ts_agg)

          time changebuildinglocation_climate_zone  sample_count units_count  \
0   2018-01-01                  ASHRAE 169-2013-1A           362         362
1   2018-01-01                  ASHRAE 169-2013-2A           721         721
2   2018-01-01                  ASHRAE 169-2013-2B           355         355
3   2018-01-01                  ASHRAE 169-2013-3A          1271        1271
4   2018-01-01                  ASHRAE 169-2013-3B           365         365
..         ...                                 ...           ...         ...
355 2018-12-01                            T24-CEC5            94          94
356 2018-12-01                            T24-CEC6            22          22
357 2018-12-01                            T24-CEC7           143         143
358 2018-12-01                            T24-CEC8           167         167
359 2018-12-01                            T24-CEC9           163         163

    rows_per_sample  electricity_heating_kwh
0              2976             1.874540e+05
1              2976             7.236298e+06
2              2976             1.990981e+06
3              2976             2.879234e+07
4              2976             2.188927e+06
..              ...                      ...
355            2976             1.305064e+06
356            2976             1.378554e+05
357            2976             1.495813e+06
358            2976             1.262215e+06
359            2976             2.673578e+06

[360 rows x 6 columns]

In [10]:
result = my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             annual_only=False,
                             include_savings=True,
                             include_baseline=True,
                             include_upgrade=True,
                             get_query_only=False)
print(result)

                     time  sample_count  units_count  \
0     2018-01-01 00:15:00         10476        10476
1     2018-01-01 00:30:00         10476        10476
2     2018-01-01 00:45:00         10476        10476
3     2018-01-01 01:00:00         10476        10476
4     2018-01-01 01:15:00         10476        10476
...                   ...           ...          ...
35035 2018-12-31 23:00:00         10476        10476
35036 2018-12-31 23:15:00         10476        10476
35037 2018-12-31 23:30:00         10476        10476
35038 2018-12-31 23:45:00         10476        10476
35039 2019-01-01 00:00:00         10476        10476

       electricity_heating_kwh__baseline  electricity_heating_kwh__upgrade  \
0                          148097.855523                     146644.923577
1                          150639.973940                     149161.628578
2                          153675.436235                     152326.288008
3                          156372.755189                     155042.306053
4                          155214.387546                     153924.114566
...                                  ...                               ...
35035                       67071.615089                      66464.315870
35036                       66447.071670                      65819.072259
35037                       66809.981943                      66203.432928
35038                       67397.005424                      66876.495433
35039                       69087.741211                      68695.955151

       electricity_heating_kwh__savings
0                           1452.931946
1                           1478.345362
2                           1349.148227
3                           1330.449136
4                           1290.272980
...                                 ...
35035                        607.299218
35036                        627.999411
35037                        606.549015
35038                        520.509991
35039                        391.786060

[35040 rows x 6 columns]

In [11]:
my_run.save_cache()

INFO:buildstock_query.query_core:15 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl

In [12]:
my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             group_by=['changebuildinglocation_climate_zone'],
                             annual_only=False,
                             include_savings=True,
                             include_baseline=False,
                             include_upgrade=False,
                             get_query_only=False)

INFO:pyathena.pandas.result_set:Reading 79453434 bytes from S3 in full mode using python engine

,time,sample_count,units_count,electricity_heating_kwh__savings,changebuildinglocation_climate_zone
0,2018-01-01 00:15:00,362,362,0.349747,ASHRAE 169-2013-1A
1,2018-01-01 00:30:00,362,362,0.239264,ASHRAE 169-2013-1A
2,2018-01-01 00:45:00,362,362,-0.001893,ASHRAE 169-2013-1A
3,2018-01-01 01:00:00,362,362,0.125232,ASHRAE 169-2013-1A
4,2018-01-01 01:15:00,362,362,-0.005029,ASHRAE 169-2013-1A
...,...,...,...,...,...
1051195,2018-12-31 23:00:00,130,130,0.473219,T24-CEC9
1051196,2018-12-31 23:15:00,130,130,0.455798,T24-CEC9
1051197,2018-12-31 23:30:00,130,130,0.442982,T24-CEC9
1051198,2018-12-31 23:45:00,130,130,0.425980,T24-CEC9
1051199,2019-01-01 00:00:00,130,130,0.419135,T24-CEC9

In [13]:
result = my_run.query(upgrade_id=2, enduses=['electricity_heating_kwh'],
                             group_by=['changebuildinglocation_climate_zone'],
                             #restrict=[('in.state', ['VT'])],
                             get_quartiles=True,
                             annual_only=True,
                             include_savings=True,
                             get_query_only=False)
print(result)

    sample_count  units_count  electricity_heating_kwh__upgrade  \
0            173          173                      4.071361e+05
1            115          115                      1.273817e+06
2             92           92                      2.546142e+06
3            438          438                      2.435752e+07
4             64           64                      2.461850e+06
5            308          308                      2.399288e+07
6            110          110                      5.817347e+06
7             20           20                      1.430656e+06
8            454          454                      1.028741e+08
9            112          112                      1.031718e+07
10           238          238                      3.650869e+07
11            25           25                      4.286214e+06
12           120          120                      1.953001e+07
13            22           22                      4.219544e+06
14             3            3                      2.880556e+03
15            40           40                      4.931531e+06
16             2            2                      4.166250e+05
17            22           22                      1.467344e+06
18            20           20                      2.536114e+06
19            46           46                      2.781519e+06
20             1            1                      3.072222e+03
21            29           29                      1.278717e+06
22            13           13                      7.069944e+05
23            30           30                      6.822861e+05
24             3            3                      9.816667e+03
25             5            5                      1.360361e+05
26            41           41                      1.469039e+06
27            48           48                      2.347439e+06

    electricity_heating_kwh__savings  \
0                         433.333333
1                       40550.000000
2                       14588.888889
3                      639897.222222
4                        -180.555556
5                      274761.111111
6                       -1158.333333
7                        3727.777778
8                      136188.888889
9                       13472.222222
10                      39483.333333
11                       4727.777778
12                       9519.444444
13                      -2311.111111
14                          0.000000
15                       -808.333333
16                          0.000000
17                       -252.777778
18                         25.000000
19                       -902.777778
20                          5.555556
21                       -205.555556
22                       -411.111111
23                         77.777778
24                          0.000000
25                          0.000000
26                       -100.000000
27                       5402.777778

          electricity_heating_kwh__upgrade__quartiles  \
0   [0.0, 0.0, 0.0, 0.0, 0.0, 5.8184523809523805, ...
1   [0.0, 0.0, 0.0, 0.0, 300.42438271604937, 12561...
2   [0.0, 0.0, 0.0, 0.0, 620.4444444444445, 18945....
3   [0.0, 0.0, 0.0, 0.0, 1494.3162584627635, 50923...
4   [0.0, 0.0, 0.0, 0.0, 5326.080246913581, 37092....
5   [0.0, 0.0, 0.0, 0.0, 1031.7145376669187, 64079...
6   [0.0, 0.0, 0.0, 0.0, 1149.9228395061727, 55582...
7   [0.0, 0.0, 0.0, 0.0, 10341.666666666666, 93488...
8   [0.0, 0.0, 0.0, 0.0, 28401.730690745848, 27332...
9   [0.0, 0.0, 0.0, 0.0, 494.75308641975306, 54290...
10  [0.0, 0.0, 0.0, 0.0, 18091.16188769415, 176736...
11  [0.0, 0.0, 0.0, 0.0, 16516.666666666668, 14069...
12  [0.0, 0.0, 0.0, 0.0, 38395.833333333336, 22901...
13  [0.0, 0.0, 0.0, 0.0, 11050.0, 423625.0, 550000...
14  [0.0, 0.0, 0.0, 0.0, 791.6666666666666, 2088.8...
15  [0.0, 0.0, 0.0, 0.0, 1817.3611111111113, 52300...
16  [10736.111111111111, 10736.111111111111, 10736...
17  [0.0, 0.0, 0.0, 0.0, 12305.555555555557, 53366...
18  [0.0, 0.0, 0.0, 0.0, 4691.666666666667, 314138...
19  [0.0, 0.0, 0.0, 0.0, 912.5, 17455.555555555555...
20  [3072.222222222222, 3072.222222222222, 3072.22...
21  [0.0, 0.0, 0.0, 0.0, 1933.3333333333333, 47794...
22  [0.0, 0.0, 0.0, 0.0, 0.0, 19463.888888888887, ...
23  [0.0, 0.0, 0.0, 0.0, 0.0, 6180.555555555556, 1...
24  [0.0, 0.0, 0.0, 0.0, 0.0, 9816.666666666666, 9...
25  [0.0, 0.0, 0.0, 0.0, 0.0, 4277.777777777778, 1...
26  [0.0, 0.0, 0.0, 0.0, 13.194444444444446, 6452....
27  [0.0, 0.0, 0.0, 0.0, 2114.583333333333, 57019....

          electricity_heating_kwh__savings__quartiles  \
0   [-52.77777777777828, -2.7777777777777786, 0.0,...
1   [-158.33333333333348, -2.7777777777773736, 0.0...
2   [-602.7777777777778, -177.77777777777737, 0.0,...
3   [-2391.666666666667, -461.4722222222223, 0.0, ...
4   [-205.55555555555475, -175.0, 0.0, 0.0, 0.0, 0...
5   [-2902.777777777778, -655.5555555555555, -0.76...
6   [-4525.000000000007, -241.66666666666669, 0.0,...
7   [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 736.11111111110...
8   [-21577.77777777787, -625.444444444445, 0.0, 0...
9   [-602.7777777777737, -258.33333333333337, 0.0,...
10  [-752.7777777777777, -313.88888888888687, 0.0,...
11  [-13.888888888890506, -13.888888888890506, 0.0...
12  [-263.88888888888886, -13.888888888888893, 0.0...
13  [-5444.444444444444, -5444.444444444444, -286....
14      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
15  [-1183.3333333333333, -1183.3333333333333, 0.0...
16      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
17  [-144.44444444443798, -144.44444444443798, 0.0...
18  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.7777777777773...
19  [-1322.2222222222222, -1322.2222222222222, 0.0...
20  [5.555555555555657, 5.555555555555657, 5.55555...
21  [-150.0, -150.0, -13.88888888888889, 0.0, 0.0,...
22  [-425.0, -425.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.8...
23  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 77.7777777...
24      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
25      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
26  [-66.66666666666667, -66.66666666666667, 0.0, ...
27  [-836.1111111111111, -836.1111111111111, -27.7...

   changebuildinglocation_climate_zone
0                   ASHRAE 169-2013-1A
1                   ASHRAE 169-2013-2A
2                   ASHRAE 169-2013-2B
3                   ASHRAE 169-2013-3A
4                   ASHRAE 169-2013-3B
5                   ASHRAE 169-2013-4A
6                   ASHRAE 169-2013-4B
7                   ASHRAE 169-2013-4C
8                   ASHRAE 169-2013-5A
9                   ASHRAE 169-2013-5B
10                  ASHRAE 169-2013-6A
11                  ASHRAE 169-2013-6B
12                  ASHRAE 169-2013-7A
13                  ASHRAE 169-2013-8A
14                            T24-CEC1
15                           T24-CEC10
16                           T24-CEC11
17                           T24-CEC12
18                           T24-CEC13
19                           T24-CEC14
20                           T24-CEC15
21                           T24-CEC16
22                            T24-CEC3
23                            T24-CEC5
24                            T24-CEC6
25                            T24-CEC7
26                            T24-CEC8
27                            T24-CEC9

In [14]:
my_run.save_cache()

INFO:buildstock_query.query_core:17 queries cache saved to .bsq_cache/chiller_v3_query_cache.pkl